# Write repo CLAUDE.md from Continue rules (Claw + shared instructions)
$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$rules = Join-Path $repoRoot "continue\rules.md"
$workflow = Join-Path $repoRoot "continue\agent-workflow.md"
$dest = Join-Path $repoRoot "CLAUDE.md"

if (-not (Test-Path $rules)) {
    Write-Error "Missing $rules - run from AI.DEN repo root"
}

$header = @'
# AI.DEN agent instructions (auto-generated)

Generated by scripts/sync-claude-md.ps1 (also run from sync-continue-config.ps1).
Edit continue/rules.md and continue/agent-workflow.md instead of this file.

'@

$body = Get-Content $rules -Raw
if (Test-Path $workflow) {
    $sep = [Environment]::NewLine + "---" + [Environment]::NewLine + [Environment]::NewLine
    $body += $sep + (Get-Content $workflow -Raw)
}

Set-Content -Path $dest -Value ($header + $body.TrimEnd() + [Environment]::NewLine) -Encoding UTF8
Write-Host "Wrote $dest"
